### ISSUE TITLE
Legacy first boot

### ISSUE THREAD

**Issue by lawmanuk** [Le0xFF/VoidLinuxInstaller#17] opened 2024-07-24 23:10 UTC
Hi,

strange issue.   I've noticed that your installer only works if I set my bios to uefi only mode.

As soon as I allow legacy boot after uefi, your installer fails to install.

I have a nvme hd on a lenova laptop.

Strange problem, but thought I'd alert you

**Comment by Le0xFF** [comment] 2024-07-25 09:00
Duplicate of #5

**Closed** 2024-07-25 09:01 UTC
